
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd1
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/ncameiri/argo_sync_2
      path: app1
      #targetRevision: 8.5.1
    - repoURL: https://github.com/ncameiri/argo_sync_2
      path: app2
      #targetRevision: 8.5.1
    - repoURL: https://github.com/ncameiri/argo_sync_2
      path: app3
      #targetRevision: 8.5.1
